### ISSUE TITLE
Fighting System

### ISSUE THREAD

**Issue by medallyon** [Medallyon/backtrace-game-jam#2]
- [x] Sword
- [x] Bow
- [x] Revolver

**Comment by TKGotHub** [comment]
**Player**

- Health: 100

- Sword Damage: 25
- Sword Attack Speed: Slow

- Bow Damage: 50
- Bow Attack Speed: Slow

- Gun Damage: 10
- Gun Attack Speed: Slow

**Hitter**

- Health: 50
- Damage: 35
- Attack Speed: Slow

**Ninja**

- Health: 100
- Damage: 20
- Attack Speed: Medium

**Trapper**

- Health: 75
- Damage: 40
- Attack Speed: None

**Comment by TKGotHub** [comment]
**2nd Phase Units**

**Ballista Tower**

- Health: 200
- Damage: 50
- Attack Speed: Medium

**Demon Soldier (Waves 1-2)**

- Health: 50
- Damage: 10
- Attack Speed: Medium

**Demon Soldier (Waves 3)**

- Health: 75
- Damage: 15
- Attack Speed: Medium

**Comment by medallyon** [comment]
I don't know if these values make a lot of sense. The player has 100 HP and the most basic unit deals 35 damage/atk, meaning the player dies after 3 hits?

**Comment by TKGotHub** [comment]
> I don't know if these values make a lot of sense. The player has 100 HP and the most basic unit deals 35 damage/atk, meaning the player dies after 3 hits?

There's a few things I considered: Health regenerates slowly and there isn't exactly an army of enemies in the 1st phase of the game. If the damage is too little the player feels no threat and if it's too much is difficult for no reason.

It's not "The player dies in 3 hits" it's "The player dies in 3 consecutive hits". The player has to avoid getting swarmed (don't get surrounded), appreciate the roll function and keep an eye out for health packs when needed. In terms of the Hitter, remember it's attack speed should be slow so 1 Hitter shouldn't be able to just KO the player quickly by itself.

If you think the numbers are too high when testing the health regen, attack speed and player damage, feel free to change them  and I'll update the document appropriately.
