### ISSUE TITLE
Player Attributes

### ISSUE THREAD

**Issue by medallyon** [Medallyon/backtrace-game-jam#3]
- [x] Health
  - [x] Slow regeneration

**Inventory**

- [x] Players can only hold 2 different types of weapons.
- [ ] Players can only hold 2 different power ups.

**Movement**

- [ ] Player can dash (cover ground quickly).
- [ ] This has a cooldown of at least 2-3 seconds.

**Comment by Medallyon** [comment]
Does the player's health automatically regenerate or will they need to top up their health another way?

**Comment by medallyon** [comment]
Does the player's health automatically regenerate or will they need to top up their health another way?

**Comment by TKGotHub** [comment]
> Does the player's health automatically regenerate or will they need to top up their health another way?

The player's health can regenerate but it should be slow. We'll incentivise the player to pick up health restore items.

**Comment by TKGotHub** [comment]
**Inventory**

- Players can only hold 2 different types of weapons.
- Players can only hold 2 different power ups.

**Comment by TKGotHub** [comment]
**Movement**

- Player can dash (cover ground quickly).
- This has a cooldown of at least 2-3 seconds.
